=== WxWatch/riot-api-libraries/schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "Repo",
    "type": "object",
    "additionalProperties": false,
    "properties": {

        "owner": {
            "type": "string",
            "additionalProperties": false
        },

        "repo": {
            "type": "string",
            "additionalProperties": false
        },

        "language": {
            "type": "string",
            "additionalProperties": false
        },

        "links": {
            "type": "array",
            "additionalProperties": false,
            "items": {
                "type": "object"
            }
        },

        "metadata": {
            "type": "object"
        }
    }
}

=== WxWatch/riot-api-libraries/libraries/typescript/zedgg.json
{
    "owner": "NitashEU",
    "repo": "zed.gg",
    "language": "TypeScript",
    "links": [
        {
            "name": "npm",
            "url": "https://www.npmjs.com/package/zed.gg"
        }
    ],
    "metadata": {
        "v3": "true",
        "rate-limiter": {
            "per-region": true,
            "burst": false,
            "spread": true,
            "header-validation": true
        }
    }
}

=== WxWatch/riot-api-libraries/libraries/java/zyra.json
{
    "owner": "MingweiSamuel",
    "repo": "Zyra",
    "language": "Java",
    "links": [
        {
            "name": "Maven",
            "url": "http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.mingweisamuel.zyra%22%20AND%20a%3A%22zyra%22"
        },
        {
            "name": "Nightlies",
            "url": "http://www.mingweisamuel.com/Zyra/"
        },
        {
            "name": "Javadoc",
            "url": "http://www.mingweisamuel.com/Zyra/apidocs/"
        }
    ],
    "metadata": {
        "v3-supported": true,
        "async": true,
        "rate-limiter": true
    }
}

=== WxWatch/riot-api-libraries/libraries/php/phpriotapi2.json
{
  "owner": "fcarrascosa",
  "repo": "phpRiotApi",
  "language": "PHP",
  "links": [
    {
      "name": "The project on gitHub",
      "url": "https://github.com/fcarrascosa/phpRiotApi"
    },
    {
      "name": "The project on packagist",
      "url": "https://packagist.org/packages/fcarrascosa/riot-api-client"
    }
  ],
  "metadata": {
    "v3-supported": true,
    "author": {
      "name": "Fernando Carrascosa",
      "website": "https://fcarrascosa.es",
      "location": "Madrid/Spain",
      "twitter": "jarredethe",
      "gitHub": "fcarrascosa"
    },
    "version": "1.0.0"
  }
}
